### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skddc** [ElementsProject/lightning#2415]
### Issue and Steps to Reproduce

After upgrading our server from Ubuntu 16.04 to 18.04, I cannot compile c-lightning anymore. It fails with the following error:

```
/usr/bin/ld: tools/headerversions.o: relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:368: recipe for target 'tools/headerversions' failed
make: *** [tools/headerversions] Error 1
```

### `getinfo` output

n/a

**Comment by rustyrussell** [comment]
make clean?

**Comment by skddc** [comment]
Thanks, that did the trick!

**Comment by skddc** [comment]
Actually, it looked like it fixed it at first, but now the error message just took much longer until it appeared and it's longer:

```
/usr/bin/ld: external/libbacktrace.a(print.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(backtrace.o): relocation R_X86_64_32 against `.text' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(mmap.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(fileline.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(posix.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(elf.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(mmapio.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: external/libbacktrace.a(dwarf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:388: recipe for target 'lightningd/lightning_hsmd' failed
make: *** [lightningd/lightning_hsmd] Error 1
rm external/libwally-core/src/secp256k1/libsecp256k1.la
```

**Comment by skddc** [comment]
OK, so I tried a fresh clone of the repo, and it was able to compile from that. So I assume `make clean` is just missing something.
