### PR TITLE
libplugin: fix compilation issue on recent gccs.

### PR DESCRIPTION
**Pull request by rustyrussell**
They now use -fno-common by default, so duplicated variables cause
a link error:

/usr/bin/ld: common/utils.o:(.bss+0x10): multiple definition of `chainparams'; plugins/libplugin.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:408: plugins/autoclean] Error 1

This was introduced in 9ebfdf0b8c8faa0267cbc4c55474b968c2467c32.

Fixes: #3597
Signed-off-by: Rusty Russell <rusty@rustcorp.com.au>
Changelog-Fixed: Multiple definition of chainparams on Fedora (or other really recent gcc)

### CODE REVIEW

**Comment by niftynei** [comment]
ACK https://github.com/ElementsProject/lightning/pull/3631/commits/d9084f70ed2d3b69f4e360680ee99faf30c4f5f8
