### PR TITLE
build: fix compilation issue on OpenBSD

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
During our development, we modified the way
we report backtraces.

On a minimal configuration in OpenBSD, it seems that we no longer compile from commit a9f26b7d07 because
our conditional code is buggy.

With the following compiler

```
vultr# cc -v
OpenBSD clang version 13.0.0
Target: amd64-unknown-openbsd7.3
Thread model: posix
InstalledDir: /usr/bin
```

We have the following error

```
cc common/channel_id.c
cc common/daemon.c
common/daemon.c:218:2: error: implicit declaration of function 'add_steal_notifiers' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        add_steal_notifiers(NULL);
        ^
1 error generated.
gmake: *** [Makefile:298: common/daemon.o] Error 1
```

Reported-by: @grubles
Fixes https://github.com/ElementsProject/lightning/issues/6701

### CODE REVIEW

**Comment by grubles** [comment]
Can confirm CLN builds now. 

```
obsd$ ./lightningd/lightningd --version 
v23.08.1-212-g98c9e45

obsd$ cc --version                      
OpenBSD clang version 13.0.0
Target: aarch64-unknown-openbsd7.3
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by vincenzopalazzo** [comment]
@grubles if you ack I think the change is trivial enough that I can merge it :)

**Comment by grubles** [comment]
ACK 98c9e45
