### ISSUE TITLE
error[E0277]: the trait bound `pb::ListpeersResponse: From<&cln_rpc::model::ListpeersResponse>` is not satisfied

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/lightning#5680]
### Issue and Steps to Reproduce
Run `cargo test` on `master` (f158b529d3e4c56b70c44aaebc821c1f15477fa2). The test build fails with:

```
error[E0277]: the trait bound `pb::ListpeersResponse: From<&cln_rpc::model::ListpeersResponse>` is not satisfied
   --> cln-grpc/src/pb.rs:349:41
    |
349 |         let g: ListpeersResponse = (&u).into();
    |                                         ^^^^ the trait `From<&cln_rpc::model::ListpeersResponse>` is not implemented for `pb::ListpeersResponse`
    |
    = help: the trait `From<cln_rpc::model::ListpeersResponse>` is implemented for `pb::ListpeersResponse`
    = note: required because of the requirements on the impl of `Into<pb::ListpeersResponse>` for `&cln_rpc::model::ListpeersResponse`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `cln-grpc` due to previous error
```

Git bisection shows that this build failure was introduced in b13ab8de3ae21fd22d09dcfb3ac6a2999764b2ba.

**Comment by whitslack** [comment]
Changing `(&u).into()` to `u.into()` makes the test build successfully. I don't know enough about Rust to know if this is the correct fix, however.

**Comment by whitslack** [comment]
This was fixed in 93c95056a31f8138cb036a35091dc9db04206c9b.
