### ISSUE TITLE
compilation error on alpine:3.13.6 in a docker container

### ISSUE THREAD

**Issue by vincenzopalazzo** [ElementsProject/lightning#4918]
I'm running the official version of c-lightning v0.10.2 and compiling it on alpine, but I receive the following compilation error

```
cc cli/test/run-large-input.c
In file included from /usr/include/fortify/strings.h:22,
                 from /usr/include/string.h:57,
                 from /usr/include/fortify/string.h:22,
                 from ccan/ccan/str/str.h:5,
                 from ccan/ccan/tal/tal.h:8,
                 from ./common/amount.h:5,
                 from cli/test/run-human-mode.c:2:
/usr/include/fortify/unistd.h:110:1: error: 'read' undeclared here (not in a function); did you mean 'pread'?
  110 | _FORTIFY_FN(read) ssize_t read(int __f, void *__s, size_t __n)
      | ^~~~~~~~~~~
In file included from cli/test/../lightning-cli.c:22,
                 from cli/test/run-human-mode.c:27:
/usr/include/fortify/unistd.h: In function 'read':
/usr/include/fortify/unistd.h:116:9: error: called object '__orig_read' is not a function or function pointer
  116 |  return __orig_read(__f, __s, __n);
      |         ^~~~~~~~~~~
In file included from /usr/include/fortify/strings.h:22,
                 from /usr/include/string.h:57,
                 from /usr/include/fortify/string.h:22,
                 from ccan/ccan/str/str.h:5,
                 from ccan/ccan/tal/tal.h:8,
                 from ./common/amount.h:5,
                 from cli/test/run-human-mode.c:2:
/usr/include/fortify/unistd.h:110:1: note: declared here
  110 | _FORTIFY_FN(read) ssize_t read(int __f, void *__s, size_t __n)
      | ^~~~~~~~~~~
make: *** [Makefile:279: cli/test/run-human-mode.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from /usr/include/fortify/strings.h:22,
                 from /usr/include/string.h:57,
                 from /usr/include/fortify/string.h:22,
                 from ccan/ccan/str/str.h:5,
                 from ccan/ccan/tal/tal.h:8,
                 from ./common/amount.h:5,
                 from cli/test/run-large-input.c:2:
/usr/include/fortify/unistd.h:110:1: error: 'read' undeclared here (not in a function); did you mean 'pread'?
  110 | _FORTIFY_FN(read) ssize_t read(int __f, void *__s, size_t __n)
      | ^~~~~~~~~~~
In file included from cli/test/../lightning-cli.c:22,
                 from cli/test/run-large-input.c:27:
/usr/include/fortify/unistd.h: In function 'read':
/usr/include/fortify/unistd.h:116:9: error: called object '__orig_read' is not a function or function pointer
  116 |  return __orig_read(__f, __s, __n);
      |         ^~~~~~~~~~~
In file included from /usr/include/fortify/strings.h:22,
                 from /usr/include/string.h:57,
                 from /usr/include/fortify/string.h:22,
                 from ccan/ccan/str/str.h:5,
                 from ccan/ccan/tal/tal.h:8,
                 from ./common/amount.h:5,
                 from cli/test/run-large-input.c:2:
/usr/include/fortify/unistd.h:110:1: note: declared here
  110 | _FORTIFY_FN(read) ssize_t read(int __f, void *__s, size_t __n)
      | ^~~~~~~~~~~
make: *** [Makefile:279: cli/test/run-large-input.o] Error 1

```

**Comment by ldipenti** [comment]
I'm seeing the same thing, have a Dockefile using alpine:3.12 that worked with c-lightning 0.10.0 but I'm getting the same error when trying to build 0.10.2

**Comment by vincenzopalazzo** [comment]
HI @ldipenti,

I'm not sure what is the problem here, but luckily the problem is only in the test, so I fixed just removed the test file.

You can see my solution here https://github.com/clightning4j/clightning4j-node/blob/b855cbadae51760657438021ecb3c02c7f20c398/0.10.2/Dockerfile#L32

**Comment by ldipenti** [comment]
Good catch! worked like a charm, thank you @vincenzopalazzo !

**Comment by vincenzopalazzo** [comment]
Mh @cdecker, I miss some things here?

I fixed the error by removing the test directory, before compiling lightning. But I didn't catch yet the compiler error. I think it is related to alpine on docker

**Comment by ldipenti** [comment]
I think one immediate solution would be to avoid compiling tests on production builds, but also adjust the tooling so that they detect these kind of lib incompatibilities.
