### PR TITLE
Fix peer_gossip_probe_nannounces compilation error on OSX 10.14.6

### PR DESCRIPTION
**Pull request by willcl-ark**
Fixes https://github.com/ElementsProject/lightning/issues/3162

I don't understand enough to know the implications of this change, but I do know that with it it builds on OSX 10.14.6 OK.

Signed-off-by: willcl-ark <will8clark@gmail.com>

### CODE REVIEW

**Comment by willcl-ark** [comment]
Much like Travis is finding by the looks of things, it seems that this change creates an error on my Debian machine.

File: gossipd/seeker.c [hunk 1]
```diff
@@ -563,7 +563,7 @@ static void peer_gossip_probe_nannounces(struct seeker *seeker)
 
 	peer = random_seeker(seeker, peer_can_take_scid_query);
 	set_state(seeker, PROBING_NANNOUNCES, peer,
-		  "Probing for %zu scids at offset %zu",
+		  "Probing for %zu scids at offset %llu",
```
Comment (niftynei) [inline gossipd/seeker.c]: does using `PRIu64` fix this?
```suggestion
		  "Probing for %zu scids at offset %"PRIu64,
```

**Comment by niftynei** [comment]
as of #3158 this has been removed.
