### ISSUE TITLE
openbsd build error: common/splice_script.c

### ISSUE THREAD

**Issue by grubles** [ElementsProject/lightning#7922]
On OpenBSD 7.6 with clang 16.0.6.

```
cc common/splice_script.c
common/splice_script.c:1535:2: error: use of undeclared identifier 'errno'
        errno = 0;
        ^
common/splice_script.c:1537:6: error: use of undeclared identifier 'errno'
        if (errno || *endptr)
            ^
common/splice_script.c:1563:2: error: use of undeclared identifier 'errno'
        errno = 0;
        ^
common/splice_script.c:1565:6: error: use of undeclared identifier 'errno'
        if (errno || *endptr)
            ^
4 errors generated.
gmake: *** [Makefile:311: common/splice_script.o] Error 1
```

Builds fine on Fedora 41 with clang 19.1.5 though...

**Comment by whitslack** [comment]
It looks as though `common/splice_script.c` is including the wrong header file. POSIX says the `errno` symbol is to be defined by including `<errno.h>`, not `<sys/errno.h>`. On Linux, the latter is simply a stub that delegates to the former, but this may not be so on OpenBSD.

@grubles: What do you get if you replace the `#include <sys/errno.h>` line in `common/splice_script.c` with `#include <errno.h>`?

**Comment by grubles** [comment]
Closing as #7940 should also work for OpenBSD.
