### ISSUE TITLE
Build error v26.04

### ISSUE THREAD

**Issue by Spixmaster** [ElementsProject/lightning#9074]
The new version does not build on Arch Linux with GCC 15.2.1.

```sh
...
cc common/status_wire.c
cc common/subdaemon.c
cc common/timeout.c
cc common/trace.c
cc common/tx_roles.c
cc common/utils.c
cc common/utxo.c
cc common/version.c
cc common/wallet.c
cc common/wireaddr.c
common/wireaddr.c: In function 'separate_address_and_port':
common/wireaddr.c:297:29: error: initialization discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  297 |                 char *end = strchr(arg, ']');
      |                             ^~~~~~
common/wireaddr.c:304:27: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
  304 |                 portcolon = strchr(arg, ':');
      |                           ^
cc1: all warnings being treated as errors
make: *** [Makefile:342: common/wireaddr.o] Error 1
rm ccan-tal.o ccan-err.o ccan-time.o ccan-crypto-shachain.o ccan-opt-parse.o ccan-isaac.o ccan-closefrom.o ccan-strset.o ccan-tal-link.o ccan-ilog.o ccan-rbuf.o ccan-opt-usage.o ccan-membuf.o ccan-utf8.o ccan-str.o ccan-list.o ccan-bitops.o ccan-mem.o ccan-crypto-hkdf.o ccan-crypto-siphash24.o ccan-io-fdpass.o ccan-noerr.o ccan-opt-helpers.o ccan-bitmap.o ccan-htable.o ccan-json_escape.o ccan-pipecmd.o ccan-io-poll.o ccan-timer.o ccan-crc32c.o ccan-str-base32.o ccan-tal-str.o ccan-crypto-ripemd160.o ccan-take.o ccan-tal-grab_file.o ccan-read_write_all.o ccan-rune-rune.o external/build-x86_64-pc-linux-gnu/libwally-core-build/src/secp256k1/libsecp256k1.la external/build-x86_64-pc-linux-gnu/jsmn-build/jsmn.o ccan-fdpass.o ccan-asort.o ccan-breakpoint.o ccan-json_out.o ccan-strmap.o ccan-cdump.o ccan-tal-path.o external/build-x86_64-pc-linux-gnu/libwally-core-build/src/libwallycore.la ccan-crypto-hmac.o ccan-str-hex.o ccan-ptr_valid.o ccan-isaac64.o ccan-intmap.o ccan-base64.o ccan-io-io.o ccan-rune-coding.o ccan-opt.o ccan-crypto-sha256.o
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'core-lightning-26.04-1':
error: packages failed to build: core-lightning-26.04-1
```
