### ISSUE TITLE
Attempting to build on macOS High Sierra 10.13.2

### ISSUE THREAD

**Issue by kitx** [ElementsProject/lightning#432]
Find that I can't compile c-lightning on High Sierra. Linking errors come from libwallycore.

```
ld: warning: ignoring file ./.libs/libwallycore.a, file was built for archive which is not the architecture being linked (x86_64): ./.libs/libwallycore.a
undef: _bip39_mnemonic_to_bytes
undef: _bip39_mnemonic_validate
undef: _wally_bzero
Undefined symbols for architecture x86_64:
  "_bip39_mnemonic_to_bytes", referenced from:
      _run_tests in lto.o
  "_bip39_mnemonic_validate", referenced from:
      _run_tests in lto.o
  "_wally_bzero", referenced from:
      _main in lto.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am able to compile libwallycore directly from source but I have to remove `--enable-swig-python` despite having SWIG installed.

Once I get past that I have linking errors with CCAN, which fails to import `ptr_valid.h` which is referenced from autodata.c. Any pointers gladly received.

**Comment by cdecker** [comment]
Sorry to say, I never tried to compile on macOS, since I don't have access to a machine. It appears though as if the library was compiled for a different architecture? The ccan `autodata` library is rather strange, and it also kills the clan address sanitizer as a side note. @rustyrussell may be able to add some color here.

**Comment by cdecker** [comment]
Thanks for the effort you are putting into this @kitx. I spoke with @rustyrussell and we might eventually want to remove `autodata`, also because it is causing some other issues with clang-based tooling. It is currently being used to register JSON commands and some of the `type_to_string` stuff, which we might be able to generate anyway.

**Comment by rodasmith** [comment]
I ran into this issue, too building for MacOS. libwally-core can be built separately and copied into the external/libwally-core directory, but then lightningd/lightning_hsmd can't compile:
> cc -L/usr/local/lib  hsmd/hsm.o hsmd/gen_hsm_client_wire.o common/bip32.o common/daemon_conn.o common/derive_basepoints.o common/funding_tx.o common/hash_u5.o common/io_debug.o common/key_derive.o common/msg_queue.o common/permute_tx.o common/status.o common/subdaemon.o common/type_to_string.o common/utils.o common/utxo.o common/version.o common/withdraw_tx.o bitcoin/base58.o bitcoin/block.o bitcoin/chainparams.o bitcoin/locktime.o bitcoin/pubkey.o bitcoin/pullpush.o bitcoin/script.o bitcoin/shadouble.o bitcoin/short_channel_id.o bitcoin/signature.o bitcoin/tx.o bitcoin/varint.o wire/wire_sync.o wire/wire_io.o wire/fromwire.o wire/peer_wire.o wire/towire.o wire/gen_peer_wire.o ccan-asort.o ccan-autodata.o ccan-breakpoint.o ccan-crypto-hmac.o ccan-crypto-hkdf.o ccan-crypto-ripemd160.o ccan-crypto-sha256.o ccan-crypto-shachain.o ccan-crypto-siphash24.o ccan-err.o ccan-fdpass.o ccan-htable.o ccan-ilog.o ccan-io-io.o ccan-intmap.o ccan-io-poll.o ccan-io-fdpass.o ccan-isaac.o ccan-isaac64.o ccan-list.o ccan-mem.o ccan-noerr.o ccan-opt-helpers.o ccan-opt-parse.o ccan-opt-usage.o ccan-opt.o ccan-pipecmd.o ccan-ptr_valid.o ccan-read_write_all.o ccan-str-hex.o ccan-str.o ccan-take.o ccan-tal-grab_file.o ccan-tal-path.o ccan-tal-str.o ccan-tal.o ccan-time.o ccan-timer.o  -Lexternal -lwallycore -lsecp256k1 -lsodium -ljsmn -lbase58 -lbacktrace -lm -lgmp -lsqlite3  -o lightningd/lightning_hsmd
Undefined symbols for architecture x86_64:
  "_secp256k1_ecdsa_recoverable_signature_parse_compact", referenced from:
      _fromwire_secp256k1_ecdsa_recoverable_signature in fromwire.o
  "_secp256k1_ecdsa_recoverable_signature_serialize_compact", referenced from:
      _towire_secp256k1_ecdsa_recoverable_signature in towire.o
  "_secp256k1_ecdsa_sign_recoverable", referenced from:
      _sign_invoice in hsm.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lightningd/lightning_hsmd] Error 1

**Comment by Sjors** [comment]
I somehow missed this when opening #645.

**Comment by Sjors** [comment]
Building now works, though I don't know if anyone has been able to launch it successfully, see #840.

**Comment by cdecker** [comment]
Closing since libwally was updated and doesn't include LATO anymore.
