### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by thestick613** [ElementsProject/lightning#421]
revision 307e8c0180580414b112dd7c1e79d2f7d876b879

```
cc -Werror -Wall -Wundef -Wmissing-prototypes -Wmissing-declarations -Wstrict-prototypes -Wold-style-definition -std=gnu11 -g -fstack-protector -I ccan -I external/libsodium/src/libsodium/include -I external/libwally-core/include/ -I external/libwally-core/src/secp256k1/include/ -I external/jsmn/ -I external/libbase58/ -I external/libbacktrace -I .   -DDEVELOPER=1 -DSHACHAIN_BITS=48 -DCCAN_TAKE_DEBUG=1   -c -o lightningd/bitcoind.o lightningd/bitcoind.c
In file included from lightningd/lightningd.h:12:0,
                 from lightningd/bitcoind.c:7:
./wallet/wallet.h:185:13: error: no previous prototype for ‘wallet_shachain_get_hash’ [-Werror=missing-prototypes]
 inline bool wallet_shachain_get_hash(struct wallet *w,
             ^
cc1: all warnings being treated as errors
make: *** [lightningd/bitcoind.o] Error 1

```

**Comment by cdecker** [comment]
Thanks for reporting this @thestick613, could you tell us which compiler this was built with? The function that is failing is unused currently, and will trip up `clang` for example. I have a `clang` (https://github.com/cdecker/lightning/tree/clang) branch that removes all static inlines and similar, could you try with that one again?

**Comment by thestick613** [comment]
I think it's falling back on gcc

```
gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I will try to update it to a newer version

**Comment by cdecker** [comment]
Any news on this? We have also added some cleanups that remove unused `static inline`s, so maybe it even works with gcc 4.8.4.

**Comment by thestick613** [comment]
don't know, upgraded to 16.04.

**Comment by cdecker** [comment]
Just checked this in a Ubuntu 14.04 docker image, with gcc 4.8.4, and it works :+1: 

Integration tests rely on 3.5 but after some minor fixes they run successfully.

Closing this issue for now, feel free to reopen should it show up again.
